-------------------------------------------------------------------------------
Test set: models.SightingTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 3.527 sec <<< FAILURE! - in models.SightingTest
equals_returnsTrueIfLocationAndDescriptionAreSame_true(models.SightingTest)  Time elapsed: 0.574 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.equals_returnsTrueIfLocationAndDescriptionAreSame_true(SightingTest.java:20)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.equals_returnsTrueIfLocationAndDescriptionAreSame_true(SightingTest.java:20)

sighting_instantiatesCorrectly_true(models.SightingTest)  Time elapsed: 0.834 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.sighting_instantiatesCorrectly_true(SightingTest.java:12)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.sighting_instantiatesCorrectly_true(SightingTest.java:12)

save_insertsObjectIntoDatabase_Sighting(models.SightingTest)  Time elapsed: 0.594 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.save_insertsObjectIntoDatabase_Sighting(SightingTest.java:29)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.save_insertsObjectIntoDatabase_Sighting(SightingTest.java:29)

all_returnsAllInstancesOfSighting_true(models.SightingTest)  Time elapsed: 0.839 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.all_returnsAllInstancesOfSighting_true(SightingTest.java:38)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.all_returnsAllInstancesOfSighting_true(SightingTest.java:38)

find_returnsSightingWithSameId_secondSighting(models.SightingTest)  Time elapsed: 0.686 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.find_returnsSightingWithSameId_secondSighting(SightingTest.java:52)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.90.70", user "aaxdbnmafohegw", database "dftdbh9698l7s0", SSL off
	at models.SightingTest.find_returnsSightingWithSameId_secondSighting(SightingTest.java:52)

